# Generated by Django 5.2.1 on 2025-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
