services:
  - type: web
    name: Market
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Market.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: wSxYf4DLwMrvVpYkSfmkrhEs32agjBEt
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
