services:
  - type: web
    name: Market
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      if [[ $CREATE_SUPERUSER ]];
      then
        python Market/manage.py createsuperuser --no-input
      fi
    startCommand: gunicorn Market.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: wSxYf4DLwMrvVpYkSfmkrhEs32agjBEt
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: CREATE_SUPERUSER
        value: true
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_PASSWORD
        value: your_secure_password
